sudo: required
services:
  - docker

before_install:
  - docker build -t patw0929/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run patw0929/react-test npm test -- --coverage

after_success:
  - docker build -t patw0929/udemy-docker-fib-client ./client
  - docker build -t patw0929/udemy-docker-fib-nginx ./nginx
  - docker build -t patw0929/udemy-docker-fib-server ./server
  - docker build -t patw0929/udemy-docker-fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push patw0929/udemy-docker-fib-client
  - docker push patw0929/udemy-docker-fib-nginx
  - docker push patw0929/udemy-docker-fib-server
  - docker push patw0929/udemy-docker-fib-worker
